# Welcome to Serverless!
#
# Happy Coding!

service: lag-awh

provider:
  name: aws
  runtime: nodejs6.10
  region: ${opt:region}
  stage: ${opt:stage}

functions:
  hello:
    handler: src/challenge-handler/handler.handleChallengeEvent
    events:
      - http:
          path: hello
          method: get
