# Welcome to Serverless!
#
# Happy Coding!

service: lag-awh

provider:
  name: aws
  runtime: nodejs6.10
  region: ${opt:region}
  stage: ${opt:stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - ${self:custom.topicArns.loanCreated}
        - ${self:custom.topicArns.loanDueDate}
        - ${self:custom.topicArns.loanRenewed}
        - ${self:custom.topicArns.loanReturned}
        - ${self:custom.topicArns.requestCreated}

functions:
  challenge:
    handler: src/challenge-handler/handler.handleChallengeEvent
    events:
      - http:
          path: ''
          method: get
    tags:
      serverless: true
      environment: ${self:custom.environmentNames.${opt:stage}}
      service: library-api-gateway
      sub-service: webhook-handler
  webhook:
    handler: src/webhook-handler/handler.handleWebhookEvent
    events:
      - http:
          path: ''
          method: post
    environment:
      ALMA_SECRET_KEY_NAME: /library-api-gateway/webhook-handler/shared-secret
      LoanCreatedTopicArn: ${self:custom.topicArns.loanCreated}
      LoanDueDateTopicArn: ${self:custom.topicArns.loanDueDate}
      LoanRenewedTopicArn: ${self:custom.topicArns.loanRenewed}
      LoanReturnedTopicArn: ${self:custom.topicArns.loanReturned}
      RequestCreatedTopicArn:  ${self:custom.topicArns.requestCreated}
    role: webhookHandlerRole
    tags:
      serverless: true
      environment: ${self:custom.environmentNames.${opt:stage}}
      service: library-api-gateway
      sub-service: webhook-handler

resources:
  Resources:
    webhookHandlerRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${opt:stage}-AllowGetSSMParameters-Policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                Effect: Allow
                Action: 
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                Resource: arn:aws:ssm:eu-west-2:#{AWS::AccountId}:parameter/library-api-gateway/webhook-handler/*
          - PolicyName: ${self:service}-${opt:stage}-AllowKMSKeyAccess-Policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                Effect: Allow
                Action:
                  - kms:GenerateDataKey
                  - kms:Encrypt
                  - kms:Decrypt
                Resource: ${self:custom.KeyArns.${opt:stage}}
    loanCreatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: AlmaLoanCreated
    loanDueDateTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: AlmaLoanDueDate
    loanRenewedTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: AlmaLoanRenewed
    loanReturnedTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: AlmaLoanReturned
    requestCreatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: AlmaRequestCreated
  Outputs:
    LoanCreatedTopicArn:
      Description: Arn for Loan Created Topic
      Value: ${self:custom.topicArns.loanCreated}
      Export:
        Name: ${self:service}:${opt:stage}:LoanCreatedTopicArn
    LoanDueDateTopicArn:
      Description: Arn for Loan Due Date Topic
      Value: ${self:custom.topicArns.loanDueDate}
      Export:
        Name: ${self:service}:${opt:stage}:LoanDueDateTopicArn
    LoanRenewedTopicArn:
      Description: Arn for Loan Renewed Topic
      Value: ${self:custom.topicArns.loanRenewed}
      Export:
        Name: ${self:service}:${opt:stage}:LoanRenewedTopicArn
    LoanReturnedTopicArn:
      Description: Arn for Loan Returned Topic
      Value: ${self:custom.topicArns.loanReturned}
      Export:
        Name: ${self:service}:${opt:stage}:LoanReturnedTopicArn
    RequestCreatedTopicArn:
      Description: Arn for Request Created Topic
      Value: ${self:custom.topicArns.requestCreated}
      Export:
        Name: ${self:service}:${opt:stage}:RequestCreatedTopicArn

custom:
  KeyArns:
    dev: ${env:KEY_ARN_DEV}
    stg: ${env:KEY_ARN_STG}
    prod: ${env:KEY_ARN_PROD}
  environmentNames:
    dev: development
    stg: staging
    prod: production
  topicArns:
    loanCreated:
      "Fn::Join": 
          - ":"
          - - "arn:aws:sns"
            - Ref: "AWS::Region"
            - Ref: "AWS::AccountId"
            - "Fn::GetAtt": [loanCreatedTopic, TopicName]
    loanDueDate:
      "Fn::Join": 
        - ":"
        - - "arn:aws:sns"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "Fn::GetAtt": [loanDueDateTopic, TopicName]
    loanRenewed:
      "Fn::Join": 
        - ":"
        - - "arn:aws:sns"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "Fn::GetAtt": [loanRenewedTopic, TopicName]
    loanReturned:
      "Fn::Join": 
        - ":"
        - - "arn:aws:sns"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "Fn::GetAtt": [loanReturnedTopic, TopicName]
    requestCreated:
      "Fn::Join": 
        - ":"
        - - "arn:aws:sns"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "Fn::GetAtt": [requestCreatedTopic, TopicName]

plugins:
  - serverless-pseudo-parameters
              
      
